### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by floridaman** [defenseunicorns/narwhal-delivery-iac-swf-reference-deployment#18]
# Background
For the purposes of facilitating cross-team collaboration, promoting internal re-use, and ensuring architectural clarity it is important that Narwhal code repositories meet the minimum standards in regard to included information.

# Acceptance Criteria
- Readme file exists at root of repository that meets Narwhal minimum standards

# Reference
- https://github.com/defenseunicorns/task-force-narwhal/blob/main/CONTRIBUTING.md#readme

**Comment by floridaman** [comment]
Feel free to argue with ANY of the requirements in regard to the readme. I just ask that you update the contribution guide.

**Comment by zack-is-cool** [comment]
Completed?
