### ISSUE TITLE
Integrate IDAM into SWF

### ISSUE THREAD

**Issue by floridaman** [defenseunicorns/narwhal-delivery-iac-swf-reference-deployment#24]
# Acceptance Criteria
- [x] Integrate IDAM solution into SWF
- [x] Verify SSO for each item in package list

# Package List
- [x] Artifactory
- [x] Jenkins
- [x] Jira
- [x] Confluence
- [x] Gitlab
- [x] Mattermost
- [x] Sonarqube

# Integrated into Reference Deployment
- [x] Artifactory
- [x] Jenkins
- [x] Jira
- [x] Confluence
- [x] Gitlab
- [x] Mattermost
- [x] Sonarqube

**Comment by Michael-Kruggel** [comment]
Looks like Jira/Confluence are not able to integrate SSO via helm chart: 
https://community.atlassian.com/t5/Jira-Service-Management/is-it-possible-to-enable-SAML-SSO-using-JIRA-DC-helm-chart/qaq-p/2132967

**Comment by Michael-Kruggel** [comment]
- Added the secret generation needed to add jira and confluence to keycloak. Will require them to be manual steps per the comment above. 

- Added a link to Atlassian documentation that outlines how to add to keycloak manually for jira and confluence
